### ISSUE TITLE
User data script is failing over new PIP version

### ISSUE THREAD

**Issue by RSchumacher13** [npalm/terraform-aws-gitlab-runner#279]
Good evening,

* We can't deploy our runners anymore because of this w-e pip update. (21.0)
* We are using the latest tagged revision of this module.

The module's userdata seems to only download the latest pip stable version (it bumped up on the 25th of January) via this URI:
`https://bootstrap.pypa.io/get-pip.py`

See the error below (It didn't occur before the 25th of January) :
```bash 
<13>Jan 25 15:31:57 user-data: + curl --fail --retry 6 -O https://bootstrap.pypa.io/get-pip.py
<13>Jan 25 15:31:57 user-data:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
<13>Jan 25 15:31:57 user-data:                                  Dload  Upload   Total   Spent    Left  Speed
<13>Jan 25 15:31:57 user-data: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1883k  100 1883k    0     0  27.4M      0 --:--:-- --:--:-- --:--:-- 27.4M
<13>Jan 25 15:31:57 user-data: + python get-pip.py --user
<13>Jan 25 15:31:58 user-data: Traceback (most recent call last):
<13>Jan 25 15:31:58 user-data:   File "get-pip.py", line 24226, in <module>
<13>Jan 25 15:31:58 user-data:     main()
<13>Jan 25 15:31:58 user-data:   File "get-pip.py", line 199, in main
<13>Jan 25 15:31:58 user-data:     bootstrap(tmpdir=tmpdir)
<13>Jan 25 15:31:58 user-data:   File "get-pip.py", line 82, in bootstrap
<13>Jan 25 15:31:58 user-data:     from pip._internal.cli.main import main as pip_entry_point
<13>Jan 25 15:31:58 user-data:   File "/tmp/tmpWuyiXp/pip.zip/pip/_internal/cli/main.py", line 60
<13>Jan 25 15:31:58 user-data:     sys.stderr.write(f"ERROR: {exc}")
<13>Jan 25 15:31:58 user-data:                                    ^
<13>Jan 25 15:31:58 user-data: SyntaxError: invalid syntax
[   18.767377] cloud-init[2412]: Jan 25 15:31:58 cloud-init[2412]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
[   18.770168] cloud-init[2412]: Jan 25 15:31:58 cloud-init[2412]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
[   18.772153] cloud-init[2412]: Jan 25 15:31:58 cloud-init[2412]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
ci-info: +++++++++++++++++++++Authorized keys from /home/ec2-user/.ssh/authorized_keys for user ec2-user++++++++++++++++++++++
ci-info: +---------+-------------------------------------------------+---------+---------------------------------------------+
```

We are trying to work around the issue through the: `userdata_pre_install` variable but this is clearly not the path we want to follow.

Any assistance would be much appreciated.

**Comment by npalm** [comment]
Problem is caused by the script for eip introduced in #161 and #165. Assigning eips is usefull for public subnets.
